# Default configuration file for Metador.
#
# You can and should override some of those values in your own config.
# All entries that are missing in your config will take the following default values.
#
# For readability, you can remove everything that you do not need to change.
##########################################################################################

[metador]
# Site where metador is served (without trailing slash)
site = 'http://localhost:8000'
# The endpoint URL for file uploads from client. Must be accessible from client.
# It depends on the -base-path of tusd and the way you proxy/route/serve requests to it.
tusd_endpoint = 'http://localhost:1080/files/'
# dataset location (will have subdirs "staging" and "complete")
data_dir = 'metador_datasets'
# after that many hours the non-completed datasets have expired and can be cleaned up
incomplete_expire = 48
# file where logs go
logfile = 'metador.log'

################

[orcid]
# Enable ORCID support
enabled = false
# If provided, the following file should contain the ORCIDs of permitted users.
# If filename is empty, anyone with an ORCID can use your instance.
# If filename is non-empty, but the file itself is empty, then _no one_ can use the instance.
allowlist_file = ''
# You need to get API credentials for your Metador instance in your ORCID account. See:
# https://info.orcid.org/documentation/api-tutorials/api-tutorial-get-and-authenticated-orcid-id/#Get_some_client_credentials
client_id = ''
client_secret = ''

# If true, uses the sandbox servers provided by ORCID (only useful for developers)
sandbox = false

################

[uvicorn]
# The host and port used by uvicorn for binding.
# These are only respected if you launch your application using `metador-cli run`.
host = '0.0.0.0'
port = 8000
reload = false
